### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by BinaryBrain** [fixme-lausanne/led-remote#1]
Is this repo dead and useless? Should we remove it?

**Comment by sasha42** [comment]
It doesn't appear to contain anything other than boilerplate code. The control system that is currently on the LED controller Pi can be [found here](https://github.com/sasha42/LED-controller).

**Comment by gcmalloc** [comment]
was a template for @sasha42 ...
I guess if he doesn't use it we can wipe it.
